"""

Revision ID: f7d65fd34d32
Revises: 6ca5ed680f7d
Create Date: 2026-03-05 09:55:00.638006

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f7d65fd34d32"
down_revision: str | Sequence[str] | None = "6ca5ed680f7d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pipelines", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("pipelines", sa.Column("deleted_by", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "pipelines", "users", ["deleted_by"], ["id"])
    op.add_column("tasks", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("tasks", sa.Column("deleted_by", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "tasks", "users", ["deleted_by"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("tasks_deleted_by_fkey", "tasks", type_="foreignkey")
    op.drop_column("tasks", "deleted_by")
    op.drop_column("tasks", "deleted_at")
    op.drop_constraint("pipelines_deleted_by_fkey", "pipelines", type_="foreignkey")
    op.drop_column("pipelines", "deleted_by")
    op.drop_column("pipelines", "deleted_at")
    # ### end Alembic commands ###
