"""

Revision ID: 99d37b31dad6
Revises: 519687538533
Create Date: 2026-03-03 10:27:47.322649

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "99d37b31dad6"
down_revision: str | Sequence[str] | None = "61f7925317a4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("additional_instruction", sa.Text(), nullable=True))
    op.drop_column("tasks", "system_prompt")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks", sa.Column("system_prompt", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.drop_column("tasks", "additional_instruction")
    # ### end Alembic commands ###
