"""

Revision ID: 00675f6e660f
Revises: 3044acb87b5f
Create Date: 2026-03-31 12:58:34.810743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00675f6e660f'
down_revision: Union[str, Sequence[str], None] = '3044acb87b5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_workflow_jobs', sa.Column('file_status', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_workflow_jobs', 'file_status')
    # ### end Alembic commands ###
