"""added_delete_key_contraint

Revision ID: 519687538533
Revises: 59ac9cf5503c
Create Date: 2026-02-27 10:26:16.698244

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "519687538533"
down_revision: str | Sequence[str] | None = "59ac9cf5503c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "uq_api_key_secret_name_not_deleted",
        "api_keys",
        ["secret_name"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "uq_workflow_name_not_deleted",
        "api_workflows",
        ["name"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_foreign_key(None, "api_workflows", "users", ["deleted_by"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "api_workflows", type_="foreignkey")
    op.drop_index(
        "uq_workflow_name_not_deleted",
        table_name="api_workflows",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(
        "uq_api_key_secret_name_not_deleted",
        table_name="api_keys",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    # ### end Alembic commands ###
