"""

Revision ID: 6ca5ed680f7d
Revises: 99d37b31dad6
Create Date: 2026-03-04 08:13:10.345655

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6ca5ed680f7d"
down_revision: str | Sequence[str] | None = "99d37b31dad6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("api_workflows", sa.Column("additional_instruction", sa.Text(), nullable=True))
    op.drop_column("api_workflows", "system_prompt")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "api_workflows", sa.Column("system_prompt", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.drop_column("api_workflows", "additional_instruction")
    # ### end Alembic commands ###
