"""Centralized error codes for consistent error handling."""


class ErrorCodes:
    """Machine-readable error codes for API responses."""

    # File Validation Errors (4xx)
    INVALID_FILE_TYPE = "ERR_INVALID_FILE_TYPE"
    FILE_SIZE_EXCEEDED = "ERR_FILE_SIZE_EXCEEDED"
    PAGE_LIMIT_EXCEEDED = "ERR_PAGE_LIMIT_EXCEEDED"
    FILE_READ_FAILED = "ERR_FILE_READ_FAILED"
    NOT_FOUND = "ERR_NOT_FOUND"
    UNAUTHENTICATED = "ERR_UNAUTHENTICATED"

    # Configuration Errors
    INVALID_SCHEMA = "ERR_INVALID_SCHEMA"
    MISSING_REQUIRED_FIELD = "ERR_MISSING_REQUIRED_FIELD"
    INVALID_TASK_TYPE = "ERR_INVALID_TASK_TYPE"
    INVALID_JSON = "ERR_INVALID_JSON"

    # OCR Processing Errors (5xx)
    OCR_PROCESSING_FAILED = "ERR_OCR_PROCESSING_FAILED"
    EXTRACTION_FAILED = "ERR_EXTRACTION_FAILED"
    CLASSIFICATION_FAILED = "ERR_CLASSIFICATION_FAILED"
    PIPELINE_EXECUTION_FAILED = "ERR_PIPELINE_EXECUTION_FAILED"

    # External Service Errors
    AZURE_SERVICE_ERROR = "ERR_AZURE_SERVICE"
    AWS_SERVICE_ERROR = "ERR_AWS_SERVICE"
    LLM_SERVICE_ERROR = "ERR_LLM_SERVICE"
