"""

Revision ID: 1b69b96588f9
Revises: b9dd23653222
Create Date: 2026-02-27 11:34:57.737376

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1b69b96588f9"
down_revision: str | Sequence[str] | None = "b9dd23653222"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_key_secrets",
        sa.Column("api_key_id", sa.Integer(), nullable=False),
        sa.Column("secret_value", sa.String(), nullable=False),
        sa.Column("generated_by", sa.Integer(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_by", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["api_key_id"],
            ["api_keys.id"],
        ),
        sa.ForeignKeyConstraint(
            ["generated_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["revoked_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("api_keys", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("api_keys", sa.Column("deleted_by", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "api_keys", "users", ["deleted_by"], ["id"])
    op.drop_column("api_keys", "secret_value")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "api_keys", sa.Column("secret_value", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "api_keys", type_="foreignkey")
    op.drop_column("api_keys", "deleted_by")
    op.drop_column("api_keys", "deleted_at")
    op.drop_table("api_key_secrets")
    # ### end Alembic commands ###
