"""added_api_workflow_jobs_table

Revision ID: a2ea5b12b880
Revises: 519687538533
Create Date: 2026-02-27 14:05:22.436320

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a2ea5b12b880"
down_revision: str | Sequence[str] | None = "519687538533"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_workflow_jobs",
        sa.Column("api_workflow_id", sa.Integer(), nullable=False),
        sa.Column("api_job_id", sa.String(length=255), nullable=False),
        sa.Column("api_secret_id", sa.Integer(), nullable=False),
        sa.Column("file_key", sa.String(length=255), nullable=True),
        sa.Column("file_metadata", sa.JSON(), nullable=True),
        sa.Column("job_metadata", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["api_secret_id"],
            ["api_key_secrets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["api_workflow_id"],
            ["api_workflows.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "task_api_workflow_job_runs",
        sa.Column("run_type", sa.String(length=255), nullable=False),
        sa.Column("task_id", sa.Integer(), nullable=True),
        sa.Column("api_workflow_job_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=255), nullable=False),
        sa.Column("job_rank", sa.Integer, nullable=True),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("failed_remarks", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["api_workflow_job_id"],
            ["api_workflow_jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("task_api_workflow_job_runs")
    op.drop_table("api_workflow_jobs")
    # ### end Alembic commands ###
