"""

Revision ID: 850fedc80fb7
Revises: 3a31c4b2ed10
Create Date: 2026-03-20 15:04:42.839570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '850fedc80fb7'
down_revision: Union[str, Sequence[str], None] = '3a31c4b2ed10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipelines', sa.Column('task_metadata', sa.JSON(), nullable=True))
    op.drop_index(op.f('idx_task_job_runs_run_type'), table_name='task_api_workflow_job_runs')
    op.drop_index(op.f('idx_task_job_runs_status'), table_name='task_api_workflow_job_runs')
    op.drop_index(op.f('idx_task_job_runs_status_created'), table_name='task_api_workflow_job_runs')
    op.drop_index(op.f('idx_task_job_runs_task_created'), table_name='task_api_workflow_job_runs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_task_job_runs_task_created'), 'task_api_workflow_job_runs', ['task_id', 'created_at'], unique=False)
    op.create_index(op.f('idx_task_job_runs_status_created'), 'task_api_workflow_job_runs', ['status', 'created_at'], unique=False)
    op.create_index(op.f('idx_task_job_runs_status'), 'task_api_workflow_job_runs', ['status'], unique=False)
    op.create_index(op.f('idx_task_job_runs_run_type'), 'task_api_workflow_job_runs', ['run_type'], unique=False)
    op.drop_column('pipelines', 'task_metadata')
    # ### end Alembic commands ###
