"""

Revision ID: bb80d18e9d1a
Revises: 00675f6e660f
Create Date: 2026-03-31 15:04:48.727590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb80d18e9d1a'
down_revision: Union[str, Sequence[str], None] = '00675f6e660f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_workflow_jobs', 'file_status')
    op.add_column('api_workflows', sa.Column('file_status', sa.String(length=255), nullable=True))
    op.add_column('tasks', sa.Column('file_status', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'file_status')
    op.drop_column('api_workflows', 'file_status')
    op.add_column('api_workflow_jobs', sa.Column('file_status', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
