"""

Revision ID: bd716620d2fd
Revises: 97e2d5eefd3a
Create Date: 2026-04-07 14:56:26.348189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd716620d2fd'
down_revision: Union[str, Sequence[str], None] = '97e2d5eefd3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_user_active_email'), table_name='users', postgresql_where="(status = 'ACTIVE'::user_status)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq_user_active_email'), 'users', ['email'], unique=True, postgresql_where="(status = 'ACTIVE'::user_status)")
    # ### end Alembic commands ###
