"""Centralized error codes for consistent error handling."""


class ErrorCodes:
    """Machine-readable error codes for API responses."""

    # User Account / Authentication Errors
    BLOCKED_ACCOUNT = "ERR_BLOCKED_ACCOUNT"
    INACTIVE_ACCOUNT = "ERR_INACTIVE_ACCOUNT"
    NOT_SETUP = "ERR_NOT_SETUP"
    SUSPICIOUS_ACTIVITY = "ERR_SUSPICIOUS_ACTIVITY"
    WRONG_PASSWORD = "ERR_WRONG_PASSWORD"
    USER_NOT_FOUND = "ERR_USER_NOT_FOUND"
    EXPIRED_PASSWORD = "ERR_EXPIRED_PASSWORD"
    EMAIL_NOT_VERIFIED = "ERR_EMAIL_NOT_VERIFIED"
    SESSION_EXPIRED = "ERR_SESSION_EXPIRED"
    INSUFFICIENT_PERMISSIONS = "ERR_INSUFFICIENT_PERMISSIONS"
    TOO_MANY_ATTEMPTS = "ERR_TOO_MANY_ATTEMPTS"
    INVALID_CREDENTIALS = "ERR_INVALID_CREDENTIALS"
    INVALID_TOKEN = "ERR_INVALID_TOKEN"
    TOKEN_EXPIRED = "ERR_TOKEN_EXPIRED"
    TOKEN_NOT_FOUND = "ERR_TOKEN_NOT_FOUND"
    PROFILE_NOT_SETUP = "ERR_PROFILE_NOT_SETUP"
    INVALID_RESET_TOKEN = "ERR_INVALID_RESET_TOKEN"

    # File Validation Errors (4xx)
    INVALID_FILE_TYPE = "ERR_INVALID_FILE_TYPE"
    FILE_SIZE_EXCEEDED = "ERR_FILE_SIZE_EXCEEDED"
    PAGE_LIMIT_EXCEEDED = "ERR_PAGE_LIMIT_EXCEEDED"
    EMPTY_FILE = "ERR_EMPTY_FILE"
    FILE_READ_FAILED = "ERR_FILE_READ_FAILED"
    NOT_FOUND = "ERR_NOT_FOUND"
    UNAUTHORIZED = "ERR_UNAUTHORIZED"
    FORBIDDEN = "ERR_FORBIDDEN"
    BAD_REQUEST = "ERR_BAD_REQUEST"
    TOO_MANY_REQUESTS = "ERR_TOO_MANY_REQUESTS"
    UNAUTHENTICATED = "ERR_UNAUTHENTICATED"

    # Configuration Errors
    INVALID_CONFIG = "ERR_INVALID_CONFIG"
    INVALID_SCHEMA = "ERR_INVALID_SCHEMA"
    MISSING_REQUIRED_FIELD = "ERR_MISSING_REQUIRED_FIELD"
    INVALID_TASK_TYPE = "ERR_INVALID_TASK_TYPE"
    INVALID_JSON = "ERR_INVALID_JSON"

    # OCR Processing Errors (5xx)
    OCR_PROCESSING_FAILED = "ERR_OCR_PROCESSING_FAILED"
    EXTRACTION_FAILED = "ERR_EXTRACTION_FAILED"
    CLASSIFICATION_FAILED = "ERR_CLASSIFICATION_FAILED"
    PIPELINE_EXECUTION_FAILED = "ERR_PIPELINE_EXECUTION_FAILED"

    # Storage Errors
    STORAGE_UPLOAD_FAILED = "ERR_STORAGE_UPLOAD_FAILED"
    STORAGE_DELETE_FAILED = "ERR_STORAGE_DELETE_FAILED"
    STORAGE_NOT_FOUND = "ERR_STORAGE_NOT_FOUND"

    # External Service Errors
    AZURE_SERVICE_ERROR = "ERR_AZURE_SERVICE"
    AWS_SERVICE_ERROR = "ERR_AWS_SERVICE"
    LLM_SERVICE_ERROR = "ERR_LLM_SERVICE"

    # Generic Errors
    INTERNAL_ERROR = "ERR_INTERNAL_ERROR"
    UNKNOWN_ERROR = "ERR_UNKNOWN_ERROR"

    # Pipeline inactive
    PIPELINE_CONFLICT = "ERR_PIPELINE_INACTIVE"

    # CSRF
    CSRF_TOKEN_INVALID = "ERR_CSRF_TOKEN_INVALID"
